#!/usr/bin/env sh

# Get the directory name for the files with staged changes
CHANGED_FILE=$(git diff --name-only --cached | head -n 1)
APP=${CHANGED_FILE%%/*}

COMMIT_MSG_FILE=$1
CURRENT_MSG=$(cat "$COMMIT_MSG_FILE")

# Check we're not dealing with changes in toplevel
if [ "$APP" = "$CHANGED_FILE" ]; then
  exit 0
fi

# Check this isn't already using the right style
if [ "$(head -c 1 ${COMMIT_MSG_FILE})" = '[' ]; then
  exit 0
fi


printf "[${APP}]\n>> " > "$COMMIT_MSG_FILE"
printf "$CURRENT_MSG" >> "$COMMIT_MSG_FILE"


# vim: et sw=2
