[terminal]
shell = "bash"

[general]
live_config_reload = true
import = [
    "./theme.toml",
]

[window]
# decorations = "None"
opacity = 0.95
startup_mode = "Maximized"
padding = { x = 3, y = 2 }

[scrolling]
history = 1000

[font]
normal = { family = "FantasqueSansM Nerd Font", style = "Regular" }
size = 13

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true

[bell]
animation = "EaseOutSine"
duration = 300


[keyboard]
bindings = [
    {key = "Space", mods = "Control|Shift", action = "ToggleViMode" },
    {key = "a", mods = "None", action = "ToggleViMode", mode = "Vi" },
    {key = "q", mods = "None", action = "ToggleViMode", mode = "Vi" },
    {key = "j", mods = "Control", action = "ScrollLineDown", mode = "Vi" },
    {key = "k", mods = "Control", action = "ScrollLineUp", mode = "Vi" },
    {key = "j", mods = "Control|Shift", action = "ScrollLineDown" },
    {key = "k", mods = "Control|Shift", action = "ScrollLineUp" },
]
