#!/bin/sh


error() {
  echo "$1" >&2
  exit 1
}

check_pwd() {
  if [ "${PWD%/Blue}" = "$PWD" ]; then
    local maybe_right_dir=$(dirname $(realpath "$0"))
    error \
"You're in the wrong directory! Try running this script from ${maybe_right_dir}"
  fi
}

install_configs() {
  [ "$#" -lt 2 ] && error 'Not enough arguments!'
  local operation=$1
  shift 1
  local toplevel=$PWD
  for app in $@
  do
    if [ -d "$app" ]
    then
      cd "./$app"
      pwd # debug
      if make "$operation"
      then
        echo -e "\e[1;33m[${app}] configured!\e[0m"
      fi
      cd "$toplevel"
    else
      error "[${app}] does not exist!"
    fi
  done
}

print_help() {
  echo "\
  Helper script for dealing with this repository.
  Run './blue install APP' to install the config located in APP/
  Run './blue uninstall APP' to reverse this.
  To run either of these, you must be running this script from the 'Blue'
  directory."
  exit 0
}


case $1 in
  -h|--help)
    print_help
    ;;
  install|uninstall)
    check_pwd
    install_configs $@
    exit
    ;;
  *) error 'Invalid option! Try --help instead';;
esac
