#!/usr/bin/bash

hc() {
	herbstclient "$@"
}

hc emit_hook reload

setxkbmap -option caps:escape

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Alt=Mod1
Super=Mod4

hc keybind $Super-Shift-q quit
hc keybind Super-Shift-Delete spawn systemctl poweroff
hc keybind $Super-Shift-r reload
hc keybind $Super-q close_or_remove

# applications
hc keybind $Super-Return spawn $TERMINAL
hc keybind $Super-Shift-Return spawn $TERMINAL -e tmux
hc keybind $Super-a spawn rofi -show drun
hc keybind $Super-b spawn $BROWSER
hc keybind $Super-t spawn $MAIL
hc keybind $Super-g spawn $TERMINAL -e nnn
hc keybind $Super-Shift-g spawn dolphin

# hardware stuff
hc keybind XF86AudioPlay spawn playerctl play-pause
hc keybind XF86AudioMute spawn desktopctl mute
hc keybind XF86AudioRaiseVolume spawn desktopctl vol + 2
hc keybind XF86AudioLowerVolume spawn desktopctl vol - 2
hc keybind XF86MonBrightnessUp   spawn desktopctl mon + 5
hc keybind XF86MonBrightnessDown spawn desktopctl mon - 5
# turn off "screen locking"
xset -dpms
xset s off

# basic movement in tiling and floating mode
# moving clients in tiling and floating mode
hc keybind $Super-Shift-Left  shift left
hc keybind $Super-Shift-Down  shift down
hc keybind $Super-Shift-Up    shift up
hc keybind $Super-Shift-Right shift right
hc keybind $Super-Shift-h     shift left
hc keybind $Super-Shift-j     shift down
hc keybind $Super-Shift-k     shift up
hc keybind $Super-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind Super-o and / split bottom 0.5 / cycle_all
hc keybind Super-i and / split right  0.5 / cycle_all

# resizing frames and floating clients
resizestep=0.02
hc keybind $Super-Control-h       resize left +$resizestep
hc keybind $Super-Control-j       resize down +$resizestep
hc keybind $Super-Control-k       resize up +$resizestep
hc keybind $Super-Control-l       resize right +$resizestep
hc keybind $Super-Control-Left    resize left +$resizestep
hc keybind $Super-Control-Down    resize down +$resizestep
hc keybind $Super-Control-Up      resize up +$resizestep
hc keybind $Super-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

# this must be set BEFORE creating any tags!
# this also does not set the layout of the first frame;
# this has to be set manually at the end
hc set default_frame_layout max

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Super-$key" use_index "$i"
        hc keybind "$Super-Shift-$key" and - move_index "$i" - use_index "$i"
    fi
done

# cycle through tags
L='use_index -3 --skip-visible'
D='use_index +1 --skip-visible'
U='use_index -1 --skip-visible'
R='use_index +3 --skip-visible'
hc keybind $Super-Left  $L
hc keybind $Super-Down  $D
hc keybind $Super-Up    $U
hc keybind $Super-Right $R
hc keybind $Super-h $L
hc keybind $Super-j $D
hc keybind $Super-k $U
hc keybind $Super-l $R
unset L D U R
hc keybind Super-space use_previous

# layout management
hc keybind Super-Alt-space set_attr clients.focus.floating toggle
hc keybind $Super-f fullscreen toggle
# hc keybind $Super-Shift-m set_attr clients.focus.minimized true
hc keybind $Super-Control-q remove
update_layout_panel_widget='polybar-msg action hblwm-layout hook 0'
hc keybind Super-Alt-Return and , \
	cycle_layout +1 max horizontal grid , \
	spawn $update_layout_panel_widget
herbstclient --count 0 --wait 'tag_changed|focus_changed' | \
	while read line
	do
		eval "$update_layout_panel_widget"
	done \
		& disown


# mouse
hc mouseunbind --all
hc mousebind $Super-Button1 move
hc mousebind $Super-Button2 zoom
hc mousebind $Super-Button3 resize

# focus
hc keybind Super-BackSpace   cycle_monitor
hc keybind Alt-Tab         cycle_all +1
hc keybind Alt-Shift-Tab   cycle_all -1
hc keybind Super-Tab spawn rofi -show window
hc keybind Super-w cycle +1
hc keybind Super-Shift-w cycle -1
hc keybind Super-e cycle_frame +1
hc keybind Super-u jumpto urgent

# theme
border_width=5
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#226622cc'
hc set frame_border_normal_color '#101010cc'
hc set frame_bg_normal_color '#565656aa'
hc set frame_bg_active_color '#345F0Caa'
hc set frame_border_width $border_width
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 0
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings true
hc set smart_frame_surroundings hide_all
hc set mouse_recenter_gap 0


hc attr theme.title_height 18
hc attr theme.title_when multiple_tabs
hc attr theme.title_font 'FantasqueSansM Nerd Font:pixelsize=18'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_depth 3  # space below the title's baseline
hc attr theme.active.color '#345F0Cef'
hc attr theme.title_color '#ffffff'
hc attr theme.normal.color '#323232dd'
hc attr theme.urgent.color '#7811A1dd'
hc attr theme.tab_color '#1F1F1Fdd'
hc attr theme.active.tab_color '#2B4F0Add'
hc attr theme.active.tab_outer_color '#6C8257dd'
hc attr theme.active.tab_title_color '#ababab'
hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width $border_width
hc attr theme.floating.border_width $border_width
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#789161'
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#606060'
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color '#141414'

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=center
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'


# autostarting apps
# unlock, just to be sure
hc unlock
if ! [ "$1" = 'reload' ]
then
	polybar --config=$HOME/.config/herbstluftwm/polybar.config.ini & disown
	picom --backend glx --vsync --daemon
	dunst & disown
	$HOME/.fehbg
	xss-lock -l -- i3lock --nofork -c 226622 & disown
	desktopctl autostart &
fi
hc keybind Super-s spawn polybar-msg cmd toggle
hc keybind Super-n spawn dunstctl 'close-all'

# set layout for initial frame; see tags for more info
hc set_layout max
