#!/bin/sh

swayidle -w \
    timeout 600 "notify-send swaylock 'you still there buddy?'" \
    timeout 900 "swaylock -f" \
    timeout 1200 "niri msg output eDP-1 off" resume "niri msg output eDP-1 on" \
    before-sleep 'swaylock -f'
